name: ninja_hex
description: Dart library to encode, decode and pretty print hex string
version: 2.0.0
homepage: https://github.com/ninja-dart/hex

documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.17.3
  pedantic: ^1.11.0
